-- =============================================================================
--  PORTAFOLIO / HOJA DE VIDA — Contenido administrable desde Supabase
-- =============================================================================
--  Ejecuta este script completo en Supabase → SQL Editor → New query → Run.
--  Es idempotente: se puede ejecutar varias veces (también sobre la versión
--  anterior del script) sin duplicar ni borrar datos.
--
--  Qué hace:
--   1. Crea las tablas cv_perfil, cv_conocimientos, cv_educacion y cv_proyectos
--      (prefijo cv_: no toca otras tablas que tenga el proyecto de Supabase).
--   2. Define quién puede editar: los correos de la tabla cv_editores
--      (función public.cv_puede_editar()). Revisa la sección 2.
--   3. RLS: los visitantes solo LEEN (filas visibles); los editores ven todo.
--   4. Función public.cv_guardar(): guarda el CV completo en una sola transacción
--      (la usa el editor /portafolio/editar).
--   5. Bucket público "portafolio" en Storage para la foto y las imágenes.
--   6. Carga el contenido inicial (el mismo de data/cv.ts) si las tablas están vacías.
--
--  Edición: botón «Editar» del sitio (/portafolio/editar) con una cuenta de
--  Supabase Auth cuyo correo esté en cv_editores. También puedes editar desde
--  Table Editor; el sitio se actualiza en ~1 minuto.
-- =============================================================================


-- 1) TABLAS -------------------------------------------------------------------

create table if not exists public.cv_perfil (
  id                   smallint    primary key default 1 check (id = 1), -- una sola fila
  nombre_completo      text        not null,
  nombre_corto         text        not null,
  titulo               text        not null,
  roles                text[]      not null default '{}',
  resumen              text        not null,
  sobre_mi             text[]      not null default '{}',
  foto_url             text        not null,
  disponible           boolean     not null default true,
  disponibilidad_texto text        not null default '',
  correo               text        not null,
  anios_experiencia    integer     not null default 0,
  contacto             jsonb       not null default '[]', -- [{etiqueta, valor, icono, enlace?}]
  idiomas              jsonb       not null default '[]', -- [{nombre, nivel, nota?}]
  lenguajes            jsonb       not null default '[]', -- [{nombre, nivel, nota?}]
  habilidades          text[]      not null default '{}',
  redes                jsonb       not null default '[]', -- [{nombre, url, icono}]
  empresas             text[]      not null default '{}', -- la primera es la actual
  updated_at           timestamptz not null default now()
);

comment on table public.cv_perfil is 'Portafolio: datos personales, contacto, idiomas, lenguajes, habilidades, redes y trayectoria (una sola fila).';

create table if not exists public.cv_conocimientos (
  id          bigint generated by default as identity primary key,
  titulo      text        not null,
  descripcion text        not null,
  icono       text        not null default 'sparkles',
  orden       integer     not null default 0,
  visible     boolean     not null default true,
  created_at  timestamptz not null default now()
);

comment on table public.cv_conocimientos is 'Portafolio: tarjetas de la sección Conocimientos.';
comment on column public.cv_conocimientos.icono is 'Nombre del ícono. Valores válidos: bank, briefcase, chart, check, cloud, code, cpu, database, github, globe, graduation, layers, linkedin, mail, map-pin, phone, pipeline, server, shield, sparkles, terminal, user, workflow.';

create table if not exists public.cv_educacion (
  id          bigint generated by default as identity primary key,
  institucion text        not null,
  titulo      text        not null,
  estado      text        not null default 'Graduado',
  periodo     text        not null,
  descripcion text        not null default '',
  orden       integer     not null default 0,
  visible     boolean     not null default true,
  created_at  timestamptz not null default now()
);

comment on table public.cv_educacion is 'Portafolio: historia educativa (institución, fechas, título y descripción).';

create table if not exists public.cv_proyectos (
  id           bigint generated by default as identity primary key,
  slug         text        not null unique,
  titulo       text        not null,
  resumen      text        not null,
  descripcion  text        not null default '',
  imagen_url   text        not null,
  tecnologias  text[]      not null default '{}',
  logros       text[]      not null default '{}',
  repo_url     text,
  demo_url     text,
  nota_privada text,
  orden        integer     not null default 0,
  visible      boolean     not null default true,
  created_at   timestamptz not null default now()
);

comment on table public.cv_proyectos is 'Portafolio: proyectos con imagen, resumen y detalle para el diálogo "Saber más".';
comment on column public.cv_proyectos.imagen_url is 'Ruta dentro de /public (ej. /portafolio/proyectos/x.svg) o URL pública (ej. Supabase Storage).';


-- 2) QUIÉN PUEDE EDITAR ---------------------------------------------------------
-- Solo los correos de la tabla cv_editores pueden usar el editor. Para autorizar
-- tu cuenta (la misma con la que inicias sesión en /login), ejecuta:
--   insert into public.cv_editores (email) values ('tu-correo@ejemplo.com');
-- Para quitar a alguien:
--   delete from public.cv_editores where email = 'correo@ejemplo.com';

create table if not exists public.cv_editores (
  email      text        primary key check (email = lower(email)),
  created_at timestamptz not null default now()
);

comment on table public.cv_editores is 'Portafolio: correos (en minúsculas) autorizados para usar el editor /portafolio/editar.';

-- Sin políticas: nadie la lee ni la cambia desde la API; solo la consulta cv_puede_editar().
alter table public.cv_editores enable row level security;

-- Solo la primera vez (tabla vacía): si el proyecto de Supabase ya tiene una tabla
-- public.usuarios con administradores (por ejemplo, de otra aplicación que comparte
-- la base de datos), se autorizan sus correos. Si no existe, no pasa nada.
do $$
begin
  if not exists (select 1 from public.cv_editores) and to_regclass('public.usuarios') is not null then
    execute $q$
      insert into public.cv_editores (email)
      select distinct lower(email)
      from public.usuarios
      where rol = 'admin' and activo is not false and email is not null
      on conflict do nothing
    $q$;
  end if;
exception when others then
  raise notice 'No se copiaron correos desde public.usuarios: %', sqlerrm;
end;
$$;

create or replace function public.cv_puede_editar()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.cv_editores e
    where e.email = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function public.cv_puede_editar() from public, anon;
grant execute on function public.cv_puede_editar() to authenticated;


-- 3) SEGURIDAD (RLS): lectura pública, edición solo por la función cv_guardar ---

alter table public.cv_perfil        enable row level security;
alter table public.cv_conocimientos enable row level security;
alter table public.cv_educacion     enable row level security;
alter table public.cv_proyectos     enable row level security;

drop policy if exists "cv_perfil: lectura pública" on public.cv_perfil;
create policy "cv_perfil: lectura pública"
  on public.cv_perfil for select
  to anon, authenticated
  using (true);

drop policy if exists "cv_conocimientos: lectura pública" on public.cv_conocimientos;
create policy "cv_conocimientos: lectura pública"
  on public.cv_conocimientos for select
  to anon, authenticated
  using (visible = true);

drop policy if exists "cv_educacion: lectura pública" on public.cv_educacion;
create policy "cv_educacion: lectura pública"
  on public.cv_educacion for select
  to anon, authenticated
  using (visible = true);

drop policy if exists "cv_proyectos: lectura pública" on public.cv_proyectos;
create policy "cv_proyectos: lectura pública"
  on public.cv_proyectos for select
  to anon, authenticated
  using (visible = true);

-- Los editores también ven las filas ocultas (visible = false) en el editor.
drop policy if exists "cv_conocimientos: editores ven todo" on public.cv_conocimientos;
create policy "cv_conocimientos: editores ven todo"
  on public.cv_conocimientos for select
  to authenticated
  using (public.cv_puede_editar());

drop policy if exists "cv_educacion: editores ven todo" on public.cv_educacion;
create policy "cv_educacion: editores ven todo"
  on public.cv_educacion for select
  to authenticated
  using (public.cv_puede_editar());

drop policy if exists "cv_proyectos: editores ven todo" on public.cv_proyectos;
create policy "cv_proyectos: editores ven todo"
  on public.cv_proyectos for select
  to authenticated
  using (public.cv_puede_editar());

-- Sin políticas de insert/update/delete: solo cv_guardar() (y el panel de Supabase) escriben.
grant select on public.cv_perfil, public.cv_conocimientos, public.cv_educacion, public.cv_proyectos to anon, authenticated;


-- 4) GUARDADO ATÓMICO DEL CV COMPLETO -------------------------------------------
-- Recibe el perfil y las listas completas; reemplaza el contenido en una sola
-- transacción (si algo falla, no se guarda nada). El orden de cada lista define
-- la columna "orden".

create or replace function public.cv_guardar(
  p_perfil        jsonb,
  p_conocimientos jsonb,
  p_educacion     jsonb,
  p_proyectos     jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.cv_puede_editar() then
    raise exception 'No tienes permiso para editar el portafolio.' using errcode = '42501';
  end if;

  -- Perfil (fila única)
  insert into public.cv_perfil as perfil (
    id, nombre_completo, nombre_corto, titulo, roles, resumen, sobre_mi, foto_url,
    disponible, disponibilidad_texto, correo, anios_experiencia,
    contacto, idiomas, lenguajes, habilidades, redes, empresas, updated_at
  ) values (
    1,
    p_perfil ->> 'nombre_completo',
    p_perfil ->> 'nombre_corto',
    p_perfil ->> 'titulo',
    array(select jsonb_array_elements_text(coalesce(p_perfil -> 'roles', '[]'::jsonb))),
    p_perfil ->> 'resumen',
    array(select jsonb_array_elements_text(coalesce(p_perfil -> 'sobre_mi', '[]'::jsonb))),
    p_perfil ->> 'foto_url',
    coalesce((p_perfil ->> 'disponible')::boolean, true),
    coalesce(p_perfil ->> 'disponibilidad_texto', ''),
    p_perfil ->> 'correo',
    coalesce((p_perfil ->> 'anios_experiencia')::integer, 0),
    coalesce(p_perfil -> 'contacto', '[]'::jsonb),
    coalesce(p_perfil -> 'idiomas', '[]'::jsonb),
    coalesce(p_perfil -> 'lenguajes', '[]'::jsonb),
    array(select jsonb_array_elements_text(coalesce(p_perfil -> 'habilidades', '[]'::jsonb))),
    coalesce(p_perfil -> 'redes', '[]'::jsonb),
    array(select jsonb_array_elements_text(coalesce(p_perfil -> 'empresas', '[]'::jsonb))),
    now()
  )
  on conflict (id) do update set
    nombre_completo      = excluded.nombre_completo,
    nombre_corto         = excluded.nombre_corto,
    titulo               = excluded.titulo,
    roles                = excluded.roles,
    resumen              = excluded.resumen,
    sobre_mi             = excluded.sobre_mi,
    foto_url             = excluded.foto_url,
    disponible           = excluded.disponible,
    disponibilidad_texto = excluded.disponibilidad_texto,
    correo               = excluded.correo,
    anios_experiencia    = excluded.anios_experiencia,
    contacto             = excluded.contacto,
    idiomas              = excluded.idiomas,
    lenguajes            = excluded.lenguajes,
    habilidades          = excluded.habilidades,
    redes                = excluded.redes,
    empresas             = excluded.empresas,
    updated_at           = now();

  -- Conocimientos
  delete from public.cv_conocimientos where true;
  insert into public.cv_conocimientos (titulo, descripcion, icono, orden, visible)
  select e ->> 'titulo',
         e ->> 'descripcion',
         coalesce(nullif(e ->> 'icono', ''), 'sparkles'),
         n::integer,
         coalesce((e ->> 'visible')::boolean, true)
  from jsonb_array_elements(coalesce(p_conocimientos, '[]'::jsonb)) with ordinality as t(e, n);

  -- Educación
  delete from public.cv_educacion where true;
  insert into public.cv_educacion (institucion, titulo, estado, periodo, descripcion, orden, visible)
  select e ->> 'institucion',
         e ->> 'titulo',
         coalesce(e ->> 'estado', ''),
         coalesce(e ->> 'periodo', ''),
         coalesce(e ->> 'descripcion', ''),
         n::integer,
         coalesce((e ->> 'visible')::boolean, true)
  from jsonb_array_elements(coalesce(p_educacion, '[]'::jsonb)) with ordinality as t(e, n);

  -- Proyectos
  delete from public.cv_proyectos where true;
  insert into public.cv_proyectos
    (slug, titulo, resumen, descripcion, imagen_url, tecnologias, logros, repo_url, demo_url, nota_privada, orden, visible)
  select e ->> 'slug',
         e ->> 'titulo',
         e ->> 'resumen',
         coalesce(e ->> 'descripcion', ''),
         e ->> 'imagen_url',
         array(select jsonb_array_elements_text(coalesce(e -> 'tecnologias', '[]'::jsonb))),
         array(select jsonb_array_elements_text(coalesce(e -> 'logros', '[]'::jsonb))),
         nullif(e ->> 'repo_url', ''),
         nullif(e ->> 'demo_url', ''),
         nullif(e ->> 'nota_privada', ''),
         n::integer,
         coalesce((e ->> 'visible')::boolean, true)
  from jsonb_array_elements(coalesce(p_proyectos, '[]'::jsonb)) with ordinality as t(e, n);
end;
$$;

revoke all on function public.cv_guardar(jsonb, jsonb, jsonb, jsonb) from public, anon;
grant execute on function public.cv_guardar(jsonb, jsonb, jsonb, jsonb) to authenticated;


-- 5) STORAGE: bucket público "portafolio" para la foto y las imágenes -----------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('portafolio', 'portafolio', true, 5242880, array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif'])
on conflict (id) do update set
  public = true,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "portafolio: editores leen" on storage.objects;
create policy "portafolio: editores leen"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'portafolio' and public.cv_puede_editar());

drop policy if exists "portafolio: editores suben" on storage.objects;
create policy "portafolio: editores suben"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'portafolio' and public.cv_puede_editar());

drop policy if exists "portafolio: editores actualizan" on storage.objects;
create policy "portafolio: editores actualizan"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'portafolio' and public.cv_puede_editar())
  with check (bucket_id = 'portafolio' and public.cv_puede_editar());

drop policy if exists "portafolio: editores borran" on storage.objects;
create policy "portafolio: editores borran"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'portafolio' and public.cv_puede_editar());


-- 6) DATOS INICIALES (solo se insertan si la tabla está vacía) ---------------------

insert into public.cv_perfil
  (id, nombre_completo, nombre_corto, titulo, roles, resumen, sobre_mi, foto_url,
   disponible, disponibilidad_texto, correo, anios_experiencia,
   contacto, idiomas, lenguajes, habilidades, redes, empresas)
select 1,
   'Julián De Jesús Tobón Botero',
   'Julián Tobón',
   'Arquitecto de datos · Desarrollador fullstack',
   array['Arquitecto de datos', 'Desarrollador fullstack', 'Consultor de core bancario']::text[],
   'Más de 6 años creando soluciones de datos y software para banca y empresas. Conecto el core bancario, las bases de datos y la web para que la información llegue completa, confiable y a tiempo.',
   array['Me muevo en la intersección entre los datos, los sistemas bancarios y el desarrollo web. Actualmente colaboro con Banco Actinver (México), donde diseño mapeos de datos entre Oracle FLEXCUBE y los reportes regulatorios de la CNBV y Banxico.', 'También construyo productos web de punta a punta con Next.js, TypeScript y Supabase, y automatizo tareas de bases de datos con Python y PL/SQL. Vivo en Medellín y estudio Ingeniería de Sistemas.']::text[],
   '/portafolio/perfil.svg',
   true,
   'Abierto a nuevos retos',
   'tu-correo@ejemplo.com',
   6,
   '[{"etiqueta":"Ciudad","valor":"Medellín, Colombia","icono":"map-pin"},{"etiqueta":"Correo","valor":"tu-correo@ejemplo.com","icono":"mail","enlace":"mailto:tu-correo@ejemplo.com"},{"etiqueta":"Teléfono","valor":"+57 300 000 0000","icono":"phone","enlace":"tel:+573000000000"},{"etiqueta":"Experiencia","valor":"6+ años","icono":"briefcase"}]'::jsonb,
   '[{"nombre":"Español","nivel":100,"nota":"Nativo"},{"nombre":"Inglés","nivel":70,"nota":"Intermedio"}]'::jsonb,
   '[{"nombre":"SQL · PL/SQL","nivel":95},{"nombre":"Python","nivel":90},{"nombre":"JavaScript","nivel":85},{"nombre":"Java","nivel":80},{"nombre":"TypeScript","nivel":75}]'::jsonb,
   array['Power BI y DAX', 'Oracle FLEXCUBE', 'Supabase y PostgreSQL', 'ETL y PySpark', 'Git, Jira y metodologías ágiles', 'Vercel, Railway y Cloudflare', 'Comunicación clara y trabajo en equipo']::text[],
   '[{"nombre":"GitHub","url":"https://github.com/tu-usuario","icono":"github"},{"nombre":"LinkedIn","url":"https://www.linkedin.com/in/tu-usuario","icono":"linkedin"},{"nombre":"Correo","url":"mailto:tu-correo@ejemplo.com","icono":"mail"}]'::jsonb,
   array['Banco Actinver', 'GFT Technologies', 'Stefanini', 'Sophos Solutions', 'Tata Consultancy Services', 'Michael Page', 'Universidad de Antioquia']::text[]
where not exists (select 1 from public.cv_perfil);

insert into public.cv_conocimientos (titulo, descripcion, icono, orden)
select * from (values
  ('Arquitectura de datos', 'Modelado, ETL, cargas incrementales y gobierno de datos.', 'pipeline', 1),
  ('Core bancario', 'Oracle FLEXCUBE: cuentas, préstamos, depósitos y pagos.', 'bank', 2),
  ('Reportes regulatorios', 'Mapeos de datos para la CNBV, Banxico y el IPAB.', 'shield', 3),
  ('Desarrollo fullstack', 'Next.js, React, TypeScript, Java y Python.', 'code', 4),
  ('Inteligencia de negocios', 'Power BI, DAX y modelos en estrella.', 'chart', 5),
  ('Cloud y bases de datos', 'Supabase, PostgreSQL, Oracle, Vercel y Railway.', 'cloud', 6)
) as datos (titulo, descripcion, icono, orden)
where not exists (select 1 from public.cv_conocimientos);

insert into public.cv_educacion (institucion, titulo, estado, periodo, descripcion, orden)
select * from (values
  ('Tu universidad', 'Ingeniería de Sistemas', 'En curso', 'Año de inicio – Actualidad', 'Arquitectura de software (hexagonal, por capas y microservicios), bases de datos y PostgreSQL, redes, gobierno de datos e inteligencia de negocios con Power BI.', 1),
  ('Plataforma o institución', 'Curso o certificación', 'Certificado', 'Año', 'Describe aquí un curso o una certificación relevante, por ejemplo de Oracle, Power BI o servicios en la nube.', 2),
  ('Tu colegio', 'Bachiller académico', 'Graduado', 'Año de grado', 'Formación secundaria. Puedes mencionar aquí el énfasis o un logro destacado.', 3)
) as datos (institucion, titulo, estado, periodo, descripcion, orden)
where not exists (select 1 from public.cv_educacion);

insert into public.cv_proyectos
  (slug, titulo, resumen, descripcion, imagen_url, tecnologias, logros, repo_url, demo_url, nota_privada, orden)
select * from (values
  ('prestamosv',
   'Prestamosv',
   'Sistema web para gestionar clientes, préstamos, pagos y liquidaciones.',
   'Plataforma para prestamistas que centraliza toda la cartera: clientes con sus documentos, préstamos con cálculo automático de intereses y cuotas, pagos con recibo, refinanciaciones, reportes y liquidación por prestamista, con acceso protegido por inicio de sesión.',
   '/portafolio/proyectos/prestamosv.png',
   array['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Supabase', 'PostgreSQL']::text[],
   array['Autenticación con roles (administrador, prestamista y operador) y políticas RLS.', 'Cálculo automático de intereses y cuotas, y saldos actualizados con disparadores (triggers) de PostgreSQL.', 'Reportes exportables a CSV y PDF, y liquidación por prestamista.', 'Recibos imprimibles e indicadores de cartera en el panel principal.']::text[],
   null,
   'https://prestamosv.vercel.app/login',
   null,
   1),
  ('antares-portal',
   'Antares Portal',
   'Portal de gestión logística y de talento humano para una empresa de transporte.',
   'Sistema web para una empresa de transporte en Colombia con nómina, directorio de empleados, módulos de recursos humanos y flujos de aprobación. Diseñé la arquitectura y el modelo de datos, y reorganicé el código base en módulos a lo largo de 25 fases.',
   '/portafolio/proyectos/antares.svg',
   array['JavaScript (ES Modules)', 'HTML y CSS', 'PostgreSQL', 'Supabase', 'Render']::text[],
   array['Reorganización en módulos de más de 48 000 líneas de JavaScript, en 25 fases.', 'Rediseño de la nómina, el directorio de empleados y los módulos de RR. HH.', 'Arquitectura, modelo entidad-relación y flujos de aprobación.', 'Conexión estable a PostgreSQL desde Render mediante Session Pooler.']::text[],
   null,
   null,
   'Proyecto para un cliente: el código es privado.',
   2),
  ('mapeo-regulatorio',
   'Mapeo regulatorio FLEXCUBE',
   'Mapeos de datos del core bancario hacia reportes de la CNBV, Banxico y el IPAB.',
   'Mapeos campo a campo entre Oracle FLEXCUBE Universal Banking v14, con el esquema personalizado del banco, y los reportes regulatorios mexicanos. Cada campo se documenta con su origen, su transformación y su nivel de confianza, y se valida contra reportes reales ya presentados.',
   '/portafolio/proyectos/regulatorio.svg',
   array['Oracle FLEXCUBE v14', 'SQL · PL/SQL', 'Excel', 'Jira']::text[],
   array['Libros de mapeo con niveles de confianza: confirmado, pendiente y por verificar.', 'Validaciones cruzadas contra datos reales de producción.', 'Reportes como el Catálogo Mínimo, IPAB, SISPAGOS y el reporte diario de liquidez de Banxico.', 'Hallazgos que corrigieron errores de plazo y de moneda en los mapeos hacia Banxico.']::text[],
   null,
   null,
   'Proyecto corporativo confidencial.',
   3),
  ('migracion-flexcube-sap',
   'Migración FLEXCUBE → SAP',
   'Documentación de funciones y mapeo de campos entre FLEXCUBE y SAP.',
   'Documentación sistemática de pantallas y funciones de FLEXCUBE (cuentas, clientes, préstamos y sucursales) y mapeo de campos transaccionales hacia SAP, sustentado en la documentación oficial de Oracle y en consultas a la base de datos.',
   '/portafolio/proyectos/flexcube-sap.svg',
   array['Oracle FLEXCUBE', 'SQL', 'SAP', 'Excel']::text[],
   array['22 campos transaccionales de cuentas mapeados contra la bitácora diaria.', '28 campos de nómina mapeados y validados con consultas reales.', 'Parametrización de 18 sucursales e identificación de campos que requieren UDF.', 'Corrección de más de una decena de errores de mapeo heredados.']::text[],
   null,
   null,
   'Proyecto corporativo confidencial.',
   4),
  ('despliegues-sql',
   'Generador de despliegues SQL',
   'Herramienta en Python que ordena scripts SQL y analiza sus dependencias.',
   'Programa en Python para equipos de bases de datos Oracle que determina el orden correcto de despliegue de los scripts SQL, detecta dependencias entre carpetas y genera un reporte en Excel con tablas planas, fáciles de revisar.',
   '/portafolio/proyectos/despliegues-sql.svg',
   array['Python', 'Oracle', 'SQL', 'Excel']::text[],
   array['Ordenamiento automático de despliegues según sus dependencias.', 'Análisis de dependencias cruzadas entre carpetas.', 'Reporte de Excel rediseñado con tablas planas de dependencias.']::text[],
   null,
   null,
   'Herramienta interna: el código es privado.',
   5),
  ('mundiales-power-bi',
   'Mundiales 1930–2022',
   'Tablero en Power BI con la historia de los mundiales de fútbol.',
   'Proyecto académico en equipo: un modelo en estrella construido con los datos de los mundiales de la FIFA entre 1930 y 2022, con medidas DAX y un informe de 8 páginas con resumen ejecutivo.',
   '/portafolio/proyectos/mundiales.svg',
   array['Power BI', 'DAX', 'Power Query', 'Modelo en estrella']::text[],
   array['Modelo dimensional en estrella con relaciones depuradas.', 'Corrección de medidas DAX y de la configuración regional en Power Query.', 'Informe de 8 páginas con resumen ejecutivo.']::text[],
   null,
   null,
   'Proyecto académico: el archivo .pbix está disponible previa solicitud.',
   6)
) as datos (slug, titulo, resumen, descripcion, imagen_url, tecnologias, logros, repo_url, demo_url, nota_privada, orden)
where not exists (select 1 from public.cv_proyectos);
